{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cairn.fullname" . }}
  labels:
    {{- include "cairn.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cairn.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.customMetric.enabled }}
    - type: Pods
      pods:
        metric:
          name: {{ .Values.autoscaling.customMetric.name }}
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.customMetric.targetAverageValue }}
    {{- end }}
{{- end }}
