{{- if or .Values.serve.apiKey (and .Values.bundle.verify.enabled .Values.bundle.verify.publicKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cairn.fullname" . }}
  labels:
    {{- include "cairn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.serve.apiKey }}
  api-key: {{ .Values.serve.apiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.bundle.verify.enabled .Values.bundle.verify.publicKey }}
  cairn.pub: {{ .Values.bundle.verify.publicKey | quote }}
  {{- end }}
{{- end }}
